export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const SET_USER_DATA = 'SET_USER_DATA';

// export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
// export const CREATE_NEW_CONVERSATION = 'CREATE_NEW_CONVERSATION';
// export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE';